name: Node
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.TANATLOC_SSR_AS_SUBMODULE }}
          submodules: true

      - uses: actions/setup-node@master
        with:
          node-version: '16.3.0'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn run prettier

      - name: Tests
        run: yarn run test || true

      - name: Prebuild
        run: yarn run prebuild

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=config/sonar-project.properties
