name: Submodule update

on: workflow_dispatch

jobs:
  submodule-update:
    name: Submodule update
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.TANATLOC_AS_SUBMODULE }}
          submodules: true

      - name: Submodule update
        run: |
          git submodule update --remote
          git config --global user.name 'Github Actions bot'
          git config --global user.email 'bot@tanatloc.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Submodule update [skip ci]" --allow-empty && git push
